# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 7, 13, 36, 14, 598294, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goals',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 7, 13, 36, 23, 942730, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
