# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 03:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0002_auto_20160107_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
