# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-03 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newyears', '0004_auto_20160227_0244'),
        ('goals', '0003_goals_shared_with'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goals',
            options={'verbose_name_plural': 'Goals'},
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='shared_with',
            new_name='individual_sharing',
        ),
        migrations.AddField(
            model_name='goals',
            name='group_sharing',
            field=models.ManyToManyField(related_name='group_sharing', to='newyears.NewYear'),
        ),
    ]
