# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-03 01:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20170103_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='individual_sharing',
            field=models.ManyToManyField(related_name='individual_sharing', to=settings.AUTH_USER_MODEL),
        ),
    ]
