# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-03 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20170103_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goals',
            name='year',
            field=models.IntegerField(),
        ),
    ]
