# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newyears', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newyear',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
    ]
