# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newyears', '0003_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newyear',
            name='attendees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listcomment',
            name='text',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
